#!/bin/sh
# Xcode Cloud runs this after cloning the repo, before it tries to build.
# We use it to generate ShanghaiRummy.xcodeproj from project.yml, since we
# intentionally don't commit the .xcodeproj (it's generated by XcodeGen).
#
# Reference: https://developer.apple.com/documentation/xcode/writing-custom-build-scripts
set -euo pipefail

echo "==> Installing XcodeGen"
brew install xcodegen

echo "==> Generating Xcode project from project.yml"
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

echo "==> Post-clone script complete"
